FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# chat-pwa API

API blueprint describing chat-pwa project - simple chat.

# group USER
This API group contains all functions associated with users and their connection.
        
## Přihlášení [/users]

### Nový Uživatl [POST]
+ Attributes
    + id: id
    name: Kania

+ Request (application/json)

        {
            "email": "test@test.com",
            "password": "secret",
            "passwordConfirm": "secret",
            "name": "Karel",
        }

+ Response 200 (text/html; charset=utf-8)

        User sign up was succesfull.     
                 
        
## UserList [/users]

### GetAll [GET]

+ Response 200 (application/json)

        {
            "id": "5",
            "name": "test@test.com"
        }        

+ Response 200 (application/json)