FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# chat-pwa API

API blueprint describing chat-pwa project - simple chat.

# group USER
This API group contains all functions associated with users and their connection.

## Login [/user/login]

### Login [POST]
+ Attributes
    + email: john@appleseed.com (string, required) - e-mail used as login name
    + password: secretPW (string, required) - password

+ Request (application/json)

        {
            "email": "test@test.com",
            "password": "secret",
        }

+ Response 200 (text/plain)

        User sign up was succesfull.
        
## Logout [/user/logout]
User does not send anything. Logout is done based on an active session.

### Logout [GET]

+ Response 200 (application/json)
        
+ Response 403 (text/plain)

        You are already logged out.        
        
## Sign up [/users]

### Signup [POST]
+ Attributes
    + id: id
    name: Kania

+ Request (application/json)

        {
            "email": "test@test.com",
            "password": "secret",
            "passwordConfirm": "secret",
            "name": "Karel",
        }

+ Response 200 (text/html; charset=utf-8)

        User sign up was succesfull.     
                 
        
## Login status [/users]

### Status [GET]

+ Response 200 (application/json)

        {
            "id": "5",
            "name": "test@test.com"
        }        

+ Response 200 (application/json)
